module.exports = function(sequelize, DataTypes) {
	
	var Legacy_Proposal = sequelize.define('Legacy_Proposal', {
		LegacyId: 'SMALLINT',
		Year: 'SMALLINT',
		Number: 'SMALLINT',
		Revision: 'TINYINT',
		Owner: DataTypes.STRING(40),
		Title: DataTypes.STRING(64),
		Abstract: DataTypes.TEXT,
		Department: DataTypes.STRING(60),
		AccessType: DataTypes.STRING(40),
		Category: DataTypes.STRING(250),
		ContactName: DataTypes.STRING(40),
		ContactMail: DataTypes.STRING(10),
		ContactPhone: DataTypes.STRING(15),
		ContactTitle: DataTypes.STRING(40),
		ContactEmail: DataTypes.STRING(60),
		BudgetName: DataTypes.STRING(40),
		BudgetMail: DataTypes.STRING(10),
		BudgetPhone: DataTypes.STRING(15),
		BudgetTitle: DataTypes.STRING(40),
		BudgetEmail: DataTypes.STRING(60),
		ConcurrenceName: DataTypes.STRING(40),
		ConcurrenceMail: DataTypes.STRING(10),
		ConcurrencePhone: DataTypes.STRING(15),
		ConcurrenceTitle: DataTypes.STRING(40),
		ConcurrenceEmail: DataTypes.STRING(60),
		DeanName: DataTypes.STRING(40),
		DeanMail: DataTypes.STRING(10),
		DeanPhone: DataTypes.STRING(15),
		DeanTitle: DataTypes.STRING(40),
		DeanEmail: DataTypes.STRING(60),
		SubmittedDate: DataTypes.DATE,
		Annual: DataTypes.CHAR(1),
		AnnualDate: DataTypes.DATE,
		Decision: DataTypes.STRING(40),
		PartialId: DataTypes.INTEGER,
		Metric: DataTypes.STRING(250),
		RequestedAmount: DataTypes.DECIMAL(14,2),
		Award: DataTypes.DECIMAL(14,2),
		AwardText: DataTypes.TEXT,
		Background: DataTypes.TEXT,
		Benefits: DataTypes.TEXT,
		Access: DataTypes.TEXT,
		Resources: DataTypes.TEXT,
		Timeline: DataTypes.TEXT,
		CategoryJustification: DataTypes.TEXT,
		OriginalSupplementalId: DataTypes.INTEGER,
		DepartmentalEndorsement: DataTypes.TEXT,
		StudentEndorsement: DataTypes.TEXT,
		AnnualReport: DataTypes.TEXT,
		AnnualStarted: DataTypes.DATE,
		AnnualInstalled: DataTypes.DATE,
		AnnualCompleted: DataTypes.DATE,
		AnnualAttachment: DataTypes.STRING(100),
		AnnualContactName: DataTypes.STRING(250),
		AnnualContactEmail: DataTypes.STRING(254),
		AnnualContactPhone: DataTypes.STRING(250)
	});

	return Legacy_Proposal;
};
